<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS0A4xeS\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS0A4xeS/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerS0A4xeS.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerS0A4xeS\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerS0A4xeS\App_KernelTestDebugContainer([
    'container.build_hash' => 'S0A4xeS',
    'container.build_id' => '0e799303',
    'container.build_time' => 1576805332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS0A4xeS');
