<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_post_create' => [[], ['_controller' => 'App\\Controller\\PostController::create'], [], [['text', '/posts']], [], []],
    'app_post_details' => [['id'], ['_controller' => 'App\\Controller\\PostController::details'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/posts']], [], []],
    'app_post_index' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/posts/']], [], []],
    'app_post_update' => [['id'], ['_controller' => 'App\\Controller\\PostController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/posts']], [], []],
    'app_post_delete' => [['id'], ['_controller' => 'App\\Controller\\PostController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/posts']], [], []],
    'index' => [['name'], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['variable', '-', '[^/]++', 'name', true], ['text', '/hello']], [], []],
    'mail' => [[], ['_controller' => 'App\\Controller\\DefaultController::mail'], [], [['text', '/mail']], [], []],
];
