<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxstdSB\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxstdSB/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKxstdSB.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKxstdSB\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerKxstdSB\App_KernelTestDebugContainer([
    'container.build_hash' => 'KxstdSB',
    'container.build_id' => '51cc6b69',
    'container.build_time' => 1577134496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxstdSB');
