<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG8EMIfo\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG8EMIfo/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerG8EMIfo.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerG8EMIfo\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerG8EMIfo\App_KernelTestDebugContainer([
    'container.build_hash' => 'G8EMIfo',
    'container.build_id' => 'f27dd2d1',
    'container.build_time' => 1577104642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG8EMIfo');
