<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWrYAiQK\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWrYAiQK/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerWrYAiQK.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerWrYAiQK\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerWrYAiQK\App_KernelTestDebugContainer([
    'container.build_hash' => 'WrYAiQK',
    'container.build_id' => 'c78a0712',
    'container.build_time' => 1577101020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWrYAiQK');
