<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerADkH9IL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerADkH9IL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerADkH9IL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerADkH9IL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerADkH9IL\App_KernelDevDebugContainer([
    'container.build_hash' => 'ADkH9IL',
    'container.build_id' => '0d7e8c1a',
    'container.build_time' => 1576803442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerADkH9IL');
