<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWWxix3T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWWxix3T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWWxix3T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWWxix3T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWWxix3T\App_KernelDevDebugContainer([
    'container.build_hash' => 'WWxix3T',
    'container.build_id' => '0417b194',
    'container.build_time' => 1577104569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWWxix3T');
